Add `fetch_project_from_timemanager` to `TimeManagerService`
Pinchett-i/nodeserver pull request #14
Opened 2022-10-24 13:19 UTC by Pinchett-i

2022-10-24 15:11 UTC, RoelandMatthijssens requested changes

2022-10-24 22:29 UTC, Pinchett-i commented on services/timemanager_service.mjs
> +    let response = await this.fetch_project_from_timemanager(project)
itt's the ladder , i misnamed it :+1:

2022-10-25 08:46 UTC, RoelandMatthijssens requested changes

2022-10-25 08:46 UTC, RoelandMatthijssens commented on services/timemanager_service.mjs
> +  static async fetch_project_time_regisitration_from_timemanager(project) {
typo

2022-10-25 08:46 UTC, RoelandMatthijssens commented on services/timemanager_service.mjs
> +    }))
all of this async stuff can go away, calling `time_registration.billable_hours` isn't async

2022-10-25 08:46 UTC, RoelandMatthijssens commented on services/timemanager_service.mjs
> +    await Promise.all(times.map(async time_registration => {
probably want to use `reduce` rather than `map`

2022-10-25 08:46 UTC, RoelandMatthijssens commented on services/timemanager_service.mjs
> +      path: '/api/timeregistrations/query',
is this really how you want to call the endpoint?

2022-10-26 08:22 UTC, RoelandMatthijssens approved these changes

2022-10-26 08:26 UTC, merged